apiVersion: v1
kind: PersistentVolume
metadata:
  name: tukano-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/tukano"
    type: DirectoryOrCreate